FROM node:22 as builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM node:22
WORKDIR /app
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package.json .
RUN npm install --only=production
EXPOSE 3000
CMD ["npm", "start"]

